version: '3.5'

services:

  laravel:
    build:
        context: ./
        dockerfile: Dockerfile
    # volumes:
    #   - laravel_sync:/var/www/html:nocopy
    ports:
      - "1000:80"
    links:
      - database
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_DATABASE=laravelblog
      - DB_USERNAME=root
      - DB_PASSWORD=root

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravelblog
    ports:
      - "33061:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  # laravel_sync:
  #   external: true
  mysql_data:
    driver: local